### ISSUE TITLE
The section headers of the sub sections in the PsyNeuLink content section are invisible when clicking the anchor(s)

### ISSUE THREAD

**Issue by zsinnema** [kmantel/psyneulink-sphinx-theme#3]
When clicking an "anchor" in the `psyneulink-page-level-bar` the section header is hidden because it scrolls behind the`psyneulink-breadcrumbs` fixed header.

Example of the page view after clicking "Welcome to PsyNeuLink"

![image](https://user-images.githubusercontent.com/124044/170868606-51226a8f-1876-424a-a1b7-97254724398a.png)

**Comment by kmantel** [comment]
Fixed by #4
